# Site settings

title: KevinZM # Title of your site
email: zmkevin@aliyun.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  千里之行，始于足下
baseurl: "https://kevinzm.github.io" # the subpath of your site, e.g. /blog/
url: "https://kevinzm.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

#twitter_username:     example  # Replace this with your Twitter username
github_username:      KevinZM  # Replace this with your GitHub username
#linkedin_username:    example  # Replace this with your LinkedIn username
#google_plus_username: example  # Replace this with your Google+ username
#facebook_username:    example  # Replace this with your Facebook username
#dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown
