# Setup
title:        KevinZM's Blog
tagline:      千里之行，始于足下
baseurl:      ""
paginate:     1

# About/contact
author:       ZM
  name:       Kevin
  url:        https://kevinzm.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown